- name: System setup
  hosts: techzone
  tasks:
      - name: Populate service facts
        service_facts:

      - name: Stop already existing frontend service
        ansible.builtin.systemd_service:
          state: stopped
          name: audio-transcription-frontend
        become: true
        become_user: root
        when: "'audio-transcription-frontend.service' in services"

      - name: Define micromamba prefix directory for the frontend
        ansible.builtin.set_fact:
          frontend_prefix: "/home/{{ ansible_user }}/frontend"
          cacheable: yes

      - name: Create prefix directory for frontend environment
        ansible.builtin.file:
          path: "{{ frontend_prefix }}"
          state: directory
          owner: "{{ ansible_user }}"
          mode: 0775
          recurse: yes

      - name: Create environment and install basic dependencies
        ansible.builtin.command:
          argv:
            - micromamba
            - install
            - --yes
            - "--root-prefix={{ frontend_prefix }}"
            - "--prefix={{ frontend_prefix }}"
            - --channel=defaults
            - "python={{ python_version }}"
      
      - name: Install dependencies from anaconda
        ansible.builtin.command:
          argv:
            - micromamba
            - install
            - --yes
            - "--root-prefix={{ frontend_prefix }}"
            - "--prefix={{ frontend_prefix }}"
            - --channel=rocketce
            - --channel=defaults
            - "python={{ python_version }}"
            - fastapi
            - numpy
            - pillow
            - uvicorn
        when: not use_pip | default(true) | bool
      
      - name: Install dependencies from devpi
        ansible.builtin.shell: |
          {{ frontend_prefix }}/bin/python -m pip install \
            --prefer-binary \
            --extra-index-url https://wheels.developerfirst.ibm.com/ppc64le/linux \
            fastapi \
            numpy \
            pillow \
            uvicorn
        when: use_pip | default(true) | bool

      - name: Install gradio and its dependencies
        ansible.builtin.shell: |
          {{ frontend_prefix }}/bin/python -m pip install \
            gradio \
            requests

      - name: Copy frontend-related files
        ansible.builtin.copy:
          src: "{{ item.src }}"
          dest: "{{ item.dest }}"
          owner: "{{ ansible_user }}"
          mode: u=rw,g=r,o=rwx
        loop:
          - { src: "../src/frontend.py", dest: "{{ working_directory }}/frontend.py" }
          - { src: "../src/ibm_theme.py", dest: "{{ working_directory }}/ibm_theme.py" }

      - name: Build frontend service parameter list
        ansible.builtin.set_fact:
          frontend_parameters: >-
            {% set result = [] -%}
            {% for key in frontend_argv.keys() -%}
              {% set ignored = result.extend(["--" + key, frontend_argv[key] or ""]) -%}
            {%- endfor %}
            {{ result | join(" ") }}
      
      - name: Create systemd service for frontend
        become: true
        become_user: root
        ansible.builtin.blockinfile:
          create: true
          mode: u=rw,g=r,o=r
          owner: "{{ ansible_user }}"
          path: /etc/systemd/system/audio-transcription-frontend.service
          block: |
            [Unit]
            Description=Audio Transcription Frontend Service

            [Service]
            Type=simple
            ExecStart={{ frontend_prefix }}/bin/python {{ working_directory }}/frontend.py {{ frontend_parameters }}
            User={{ ansible_user }}

            [Install]
            WantedBy=multi-user.target

      - name: Set frontend service state
        ansible.builtin.systemd_service:
          state: "{{ frontend_state | default('started') }}"
          daemon_reload: true
          name: audio-transcription-frontend
        become: true
        become_user: root
