techzone:
  hosts:
    my_host_1:
      ansible_host: <IP ADDRESS OR HOSTNAME>
      ansible_password: "<PASSWORD>"
  vars:
    ansible_user: <USERNAME>
    conda_dir: "/home/{{ ansible_user }}/micromamba"
    micromamba_location: "/usr/local/bin/micromamba"
    model_repository: ggerganov/whisper.cpp
    model_file: ggml-base.en.bin
    python_version: 3.11
    working_directory: "/home/{{ ansible_user }}/llm"
    frontend_argv:
      host: 0.0.0.0
      port: 7860
    whisper_cpp_args:
      p: 16
      t: 32
    whisper_cpp_argv:
      host: 0.0.0.0
      port: 8080
